### ISSUE TITLE
machine readable way to get diffs

### ISSUE THREAD

**Issue by guysoft** [alonmln/ILNewsDiff#27]
Its interesting to see:

        What words are most edited
        What topics are most edited.
        I think running via word2vec might be fun.

Unlike the NYT original, ILNews has multiple news sources and they behave differently.
(This might also be relevant to @hasadna  )

**Comment by alonmln** [comment]
Hi @guysoft, sorry for the late reply!
Can you give me an email address to send a copy of the database to? I'd love to cooperate on analyzing the changes

**Comment by guysoft** [comment]
admin at gnethomelinux dot com 
is mine. Or you could just publish it?

**Comment by alonmln** [comment]
Sent it, I'd rather not publish the raw data as of this time, details are in the email.
